runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /index\.html
  static_files: AutismSeniorDesign/index.html
  upload: AutismSeniorDesign/index\.html

- url: /SeniorDesign\.css
  static_files: AutismSeniorDesign/SeniorDesign.css
  upload: AutismSeniorDesign/SeniorDesign\.css

- url: /icon\.png
  static_files: AutismSeniorDesign/icon.png
  upload: AutismSeniorDesign/icon\.png

- url: /Project Plan\.pdf
  static_files: AutismSeniorDesign/Project Plan.pdf
  upload: AutismSeniorDesign/Project Plan\.pdf

- url: /Presentation\.pdf
  static_files: AutismSeniorDesign/Presentation.pdf
  upload: AutismSeniorDesign/Presentation\.pdf

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
